curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=APOE&cellType=all' > ENCORI_hg19_RBPTarget_APOE.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ATF5&cellType=all' > ENCORI_hg19_RBPTarget_ATF5.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=HTT&cellType=all' > ENCORI_hg19_RBPTarget_HTT.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=IFNG&cellType=all' > ENCORI_hg19_RBPTarget_IFNG.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=RIP140&cellType=all' > ENCORI_hg19_RBPTarget_RIP140.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=SOD1&cellType=all' > ENCORI_hg19_RBPTarget_SOD1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=STAT3&cellType=all' > ENCORI_hg19_RBPTarget_STAT3.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ITK&cellType=all' > ENCORI_hg19_RBPTarget_ITK.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=MDM2&cellType=all' > ENCORI_hg19_RBPTarget_MDM2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=HMOX2&cellType=all' > ENCORI_hg19_RBPTarget_HMOX2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=FFAR2&cellType=all' > ENCORI_hg19_RBPTarget_FFAR2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=NRN1&cellType=all' > ENCORI_hg19_RBPTarget_NRN1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=MAP3K5&cellType=all' > ENCORI_hg19_RBPTarget_MAP3K5.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=XRCC5&cellType=all' > ENCORI_hg19_RBPTarget_XRCC5.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=AR&cellType=all' > ENCORI_hg19_RBPTarget_AR.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=LEMD3&cellType=all' > ENCORI_hg19_RBPTarget_LEMD3.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PCCB&cellType=all' > ENCORI_hg19_RBPTarget_PCCB.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ACAD8&cellType=all' > ENCORI_hg19_RBPTarget_ACAD8.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=MAP3K7&cellType=all' > ENCORI_hg19_RBPTarget_MAP3K7.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=JAK2&cellType=all' > ENCORI_hg19_RBPTarget_JAK2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=RPS19&cellType=all' > ENCORI_hg19_RBPTarget_RPS19.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CAV1&cellType=all' > ENCORI_hg19_RBPTarget_CAV1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=AKT1&cellType=all' > ENCORI_hg19_RBPTarget_AKT1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=BIRC5&cellType=all' > ENCORI_hg19_RBPTarget_BIRC5.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=FYN&cellType=all' > ENCORI_hg19_RBPTarget_FYN.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CASP8&cellType=all' > ENCORI_hg19_RBPTarget_CASP8.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CDK2&cellType=all' > ENCORI_hg19_RBPTarget_CDK2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=FECH&cellType=all' > ENCORI_hg19_RBPTarget_FECH.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=STK4&cellType=all' > ENCORI_hg19_RBPTarget_STK4.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=GLCCI1&cellType=all' > ENCORI_hg19_RBPTarget_GLCCI1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=APP&cellType=all' > ENCORI_hg19_RBPTarget_APP.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PTEN&cellType=all' > ENCORI_hg19_RBPTarget_PTEN.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PKM&cellType=all' > ENCORI_hg19_RBPTarget_PKM.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=SMAD3&cellType=all' > ENCORI_hg19_RBPTarget_SMAD3.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PFKFB3&cellType=all' > ENCORI_hg19_RBPTarget_PFKFB3.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CD274&cellType=all' > ENCORI_hg19_RBPTarget_CD274.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=STK17B&cellType=all' > ENCORI_hg19_RBPTarget_STK17B.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ACADSB&cellType=all' > ENCORI_hg19_RBPTarget_ACADSB.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=FBX038&cellType=all' > ENCORI_hg19_RBPTarget_FBX038.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=TIGIT&cellType=all' > ENCORI_hg19_RBPTarget_TIGIT.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=HMOX1&cellType=all' > ENCORI_hg19_RBPTarget_HMOX1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CSK&cellType=all' > ENCORI_hg19_RBPTarget_CSK.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=MCL1&cellType=all' > ENCORI_hg19_RBPTarget_MCL1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=HAVCR2&cellType=all' > ENCORI_hg19_RBPTarget_HAVCR2.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ADAM17&cellType=all' > ENCORI_hg19_RBPTarget_ADAM17.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=NRP1&cellType=all' > ENCORI_hg19_RBPTarget_NRP1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=ADORA2A&cellType=all' > ENCORI_hg19_RBPTarget_ADORA2A.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PCCA&cellType=all' > ENCORI_hg19_RBPTarget_PCCA.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PBRM1&cellType=all' > ENCORI_hg19_RBPTarget_PBRM1.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PKLR&cellType=all' > ENCORI_hg19_RBPTarget_PKLR.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=PTPN6&cellType=all' > ENCORI_hg19_RBPTarget_PTPN6.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CBLB&cellType=all' > ENCORI_hg19_RBPTarget_CBLB.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=LAG3&cellType=all' > ENCORI_hg19_RBPTarget_LAG3.csv
curl 'http://starbase.sysu.edu.cn/api/RBPTarget/?assembly=hg19&geneType=mRNA&RBP=all&clipExpNum=5&pancancerNum=0&target=CD96&cellType=all' > ENCORI_hg19_RBPTarget_CD96.csv
